# frozen_string_literal: true
source "https://rubygems.org"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
group :jekyll_plugins do
    gem 'jekyll-feed'
    gem 'jekyll-sitemap'
    gem 'jekyll-paginate'
    gem 'jekyll-seo-tag'
    gem 'jekyll-archives'
    gem 'jekyll-redirect-from'
    gem 'tzinfo-data'
    gem 'tzinfo'
    gem "webrick"
end